testcontainers/testcontainers-rs

testcontainers/Cargo.toml

This links to travis-ci.org but our builds are on travis-ci.com.

Remove travis badge

---

images/coblox_bitcoincore/Cargo.toml
images/trufflesuite_ganachecli/Cargo.toml

Increasing the version of the testcontainers dependency is actually a
breaking changes, thus we have to bump the minor version.

Bump minor versions of images

---

images/coblox_bitcoincore/examples/get_new_address.rs
images/parity_parity/examples/list_accounts.rs
images/trufflesuite_ganachecli/examples/list_accounts.rs
testcontainers/Cargo.toml
testcontainers/examples/usage.rs
testcontainers/src/api.rs
testcontainers/src/clients/cli.rs
testcontainers/src/clients/docker_inspect_response.json
testcontainers/src/clients/mod.rs
testcontainers/src/docker_cli.rs
testcontainers/src/lib.rs

I tried to integrate a 2nd docker client next to the `Cli` and identified some necessary refactorings.
In short:
- Store only a reference to the Docker client inside a Container
- Only expose a `ports()` getter from the Docker API
Please see the commit messages for more detail.

Refactoring in preparation for integration of other Docker clients

---

cli_client/Cargo.toml
cli_client/src/cli.rs
core/Cargo.toml
core/src/container.rs
core/src/docker.rs
core/src/image.rs
core/src/lib.rs
core/src/wait_for_message.rs
images/coblox_bitcoincore/Cargo.toml
images/coblox_bitcoincore/src/lib.rs
images/parity_parity/Cargo.toml
images/parity_parity/src/image.rs
images/trufflesuite_ganachecli/Cargo.toml
testcontainers/.gitignore
testcontainers/Cargo.toml
testcontainers/src/lib.rs

This commit also directly increments all the necessary versions for
the next release.
As I was writing the documentation for the main traits + structs, I
realized that they actually expose more things publicly than needed.
Therefore, this commit also includes a breaking change for the tc_core
crate because some of the public methods are removed. For users of the
testcontainers crate, this shouldn't be noticeable though since from the
PoV of testcontainers, it is a non-breaking change and thus a
patch-release.
Fixes #6.

Add documentation for most public items

---

cli_client/Cargo.toml
cli_client/src/cli.rs
cli_client/tests/waits_before_fetching_logs.rs

We wait for at least one second before fetching the logs from a
container in order to avoid the problem of not seeing logs when we try
to get them immediately after starting the container.
Fixex #17.

Conditionally wait longer before fetching logs

---

images/parity_parity/Cargo.toml
images/parity_parity/src/image.rs
testcontainers/Cargo.toml

Allows tag to be passed when using the parity image and default to latest parity v2.1.3.
Resolves #46.

Upgrade default parity image tag

---

cli_client/src/cli.rs
cli_client/tests/waits_before_fetching_logs.rs
core/src/image.rs
images/coblox_bitcoincore/src/image.rs
images/dynamodb_local/src/image.rs
images/elasticmq/src/image.rs
images/generic/src/image.rs
images/parity_parity/src/image.rs
images/postgres/src/image.rs
images/redis/src/image.rs
images/trufflesuite_ganachecli/src/image.rs
testcontainers/tests/images.rs

Attempt to fix #57
This PR introduces:
- a new method to return env vars added to the Image trait
- environment variables handling added in the Cli
- a new method to declare custom env vars added to the GenericImage
It does not provide any solution for the non-generic images; a per-image specific solution is outside the scope of this PR.

Add environment variables

---

RELEASE_CHECKLIST.md
cli_client/Cargo.toml
core/Cargo.toml
images/coblox_bitcoincore/Cargo.toml
images/dynamodb_local/Cargo.toml
images/elasticmq/Cargo.toml
images/generic/Cargo.toml
images/parity_parity/Cargo.toml
images/postgres/Cargo.toml
images/redis/Cargo.toml
images/trufflesuite_ganachecli/Cargo.toml
testcontainers/Cargo.toml

Because of tc_core bump, all crates must be upgraded.
This version contains other functional changes for most images crates.
Related to comit-network/comit-rs#762

Bump tc_core version to 0.3.0, testcontainers to 0.5.1

---

cli_client/Cargo.toml
cli_client/src/lib.rs
core/Cargo.toml
core/src/lib.rs
images/coblox_bitcoincore/Cargo.toml
images/coblox_bitcoincore/src/lib.rs
images/dynamodb_local/Cargo.toml
images/dynamodb_local/src/lib.rs
images/elasticmq/Cargo.toml
images/elasticmq/src/lib.rs
images/generic/Cargo.toml
images/generic/src/lib.rs
images/parity_parity/Cargo.toml
images/parity_parity/src/lib.rs
images/postgres/Cargo.toml
images/postgres/src/lib.rs
images/redis/Cargo.toml
images/redis/src/lib.rs
images/trufflesuite_ganachecli/Cargo.toml
images/trufflesuite_ganachecli/src/lib.rs

After this is merged, we will need to release all those crates for the deprecation to take effect.
Part of #103.

Deprecate all microcrates

---

src/clients/cli.rs
src/core/container.rs
src/core/docker.rs
tests/images.rs

All possible ports fit within the u16 range, no need for u32.
Fixes #118.

Make `get_host_port` return a u16

---

src/clients/cli.rs
src/core.rs
src/core/image.rs
src/images/coblox_bitcoincore.rs
src/images/dynamodb_local.rs
src/images/elasticmq.rs
src/images/generic.rs
src/images/parity_parity.rs
src/images/postgres.rs
src/images/redis.rs
src/images/trufflesuite_ganachecli.rs
tests/cli_client.rs
tests/images.rs

This PR adds a `run_with_options` method that allows running a docker container with custom options instead of the currently hardcoded ones (i.e. "-d" "-P").
This permits, for example, to start a container on a predetermined port.
E.g.:
```rust
let fixed_port = get_the_port_from_somewhere();
let docker = clients::Cli::default();
let _node = docker.run_with_options(
vec!["-d", "-p", &format!("{}:5432", fixed_port)],
images::postgres::Postgres::default(),
);
```

Allow custom options on docker run

---

Cargo.toml
tests/images.rs

Wow, this project is awesome!
Here's a PR that updates the postgres dependency to match the latest one.
I ran the tests on my machine and everything but the dynamodb one passed, it looks unrelated though 🤷‍♀️
```
---- dynamodb_local_create_table stdout ----
thread 'dynamodb_local_create_table' panicked at '
expected: result[ok]
but was: result[error]<HttpDispatch(HttpDispatchError { message: "operation was canceled: connection closed before message completed" })>
```

Update postgres to 0.17

---

Cargo.toml
tests/images.rs

We used the blocking API so no async conversion is required for this.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

cargo: Upgrade reqwest 0.9 -> 0.10

---

src/clients/cli.rs
src/core/container.rs
src/core/docker.rs

To be able to test connection dropping. Also wait for commands to stop.
Resolves #164.

Allow containers to be started once stopped

---

CHANGELOG.md
src/images/postgres.rs

- Allow passing in version (note 12 is the stable verison now but kept it at 11 for backwards compat).
- Remove password in favour of just trusting any connection
- Remove strange empty struct so you can actually pass in arguments

Misc improvements to postgres image

---

.travis.yml
src/clients/cli.rs

Fixes #199
Potentially fixes - #193, #106
Changed:
- `Cli::rm()` method now blocks until command finishes executing.
Added:
- Test case to ensure that `Cli::rm()` command actually fails instead of silently succeeding.

Fix `Cli::rm` not blocking until rm is successful

---

CHANGELOG.md
src/clients/cli.rs
src/core.rs
src/core/docker.rs
src/lib.rs

Docker::run_args allows users to specify a docker network and a name
for the container. The network will be created on-demand and clean-up
in the end when the client is dropped.
Co-authored-by: Aleksandrov Vladimir <invis87@gmail.com>

Allow containers to be named and assigned to a network on startup

---

src/images/coblox_bitcoincore.rs

This is to address issue: https://github.com/testcontainers/testcontainers-rs/issues/161
Passed all existing test including coblox_bitcoincore_getnewaddress which caught my typo in types. Let me know if I need to add a test for difference address type.
Fixes #161.

Added address_type default to bech 32 to bitcoincore

---

Cargo.toml
src/core/docker.rs

The functionality can easily be replicated without adding this dependency.
Fixes #231.

Remove `derivative` dependency

---

CHANGELOG.md
src/clients/cli.rs
src/core.rs
src/core/container.rs
src/core/image.rs
src/images/coblox_bitcoincore.rs
src/images/dynamodb_local.rs
src/images/elasticmq.rs
src/images/generic.rs
src/images/mongo.rs
src/images/orientdb.rs
src/images/parity_parity.rs
src/images/postgres.rs
src/images/redis.rs
src/images/trufflesuite_ganachecli.rs
src/images/zookeeper.rs
tests/cli_client.rs
tests/images.rs

Making this feature declarative has several advantages:
- It reduces the amount of code one needs to write for a new image.
- It avoids the need for an `ImageAsync` trait once we introduce that,
see discussions in #216 for details. cc @ywalterh
- It allows for a re-usable abstraction of waiting for a specific
amount of time, which fixes #39.

Replace `wait_until_ready` with declarative `ready_conditions`

---

CHANGELOG.md
src/clients/cli.rs
src/images.rs
src/images/hello_world.rs
tests/cli_client.rs
tests/podman.rs

This change allows using podman: https://podman.io/
`podman` is a drop in CLI replacement for `docker`, so the change should be minimal.
My main usecase for this is that `docker` fails to run Postgres images in GitHub actions. When the container starts, it shuts down the database and then execs into the main database process. This gets stuck when run in Docker, probably because GitHub actions already runs inside Docker.
Switching to podman, which is available by default on Ubuntu 20.04, and also available by default on GitHub actions workers, fixes the problem.

Allow using podman

---

CHANGELOG.md
src/images/coblox_bitcoincore.rs
tests/images.rs

With the upgrade to 0.21.0 a new startup command was introduced which allows us to execute a script when the startup sequence was completed. We simply echo `bitcoind startup sequence completed.`.
This allows us to remove `-debug` which keeps the bitcoind log _clean_.
Note: this release also removed the default wallet.

Upgrade default bitcoin image version to 0.21.0

---

Cargo.toml

Looks like a dependency on openssl creeped in with the addition of shiplift. This assumed #105 still holds and that openssl is not required. It still built without the feature enabled.

Removed openssl dep

---

Cargo.toml
src/images.rs
src/images/kafka.rs
tests/kafka.rs

This PR adds a Kafka image [confluentinc/cp-kafka](https://hub.docker.com/r/confluentinc/cp-kafka/) to the crate. I was aware that there was an existing #229 and wanted to help cross the finish line, but decided to start from scratch for the following reasons:
- Other client libraries for `testcontainers`, e.g. Java, Python, and NodeJS, use `confluentinc/cp-kafka` whereas #229 uses `bitnami/kafka`. For consistency with other client libraries, this PR has chosen `confluentinc/cp-kafka`.
- #229 shells out to bash execute `kafka-console-consumer` and `kafka-console-consumer` during testing. The test in this PR uses the `rdkafka` crate to interact with a Kafka broker, illustrating how that can be done without bash.
- #229 has been inactive for the last couple of months and I needed the Kafka …

Add Kafka image confluentinc/cp-kafka

---

Cargo.toml
tests/images.rs

fix "cannot infer type" error of mongodb test
update mongodb version. Somehow, CI is actually testing with
mongodb@2.0.0-beta instead of specified 2.0.0-alpha

Fix mongodb test

---

src/clients/cli.rs
src/core/image.rs
src/images.rs
src/images/google_cloud_sdk.rs
tests/images.rs

Hey @thomaseizinger 
Certain images (eg. [google/cloud-sdk](https://hub.docker.com/layers/google/cloud-sdk/353.0.0/images/sha256-fe242b7bb1334f7ce5fa56872347dd9819f3717040e65dec9478a566b2033f0e?context=explore)) don't have an `EXPOSE` layer. I think we can make use of `--expose` option in `docker run` command for those cases. I have added a method `expose_port` in `Image` trait. It has a default implementation. So, we can implement it only for the images where it is really required. 
At the moment, I only need bigtable emulator for my usecase. But when I looked at `testcontainers-java`, I thought I can add the rest too.
What do you think of this approach? 
I only focussed on `Docker` and `Cli`. Based on our discussion, I will iterate (`expose_port` to `expose_ports`, tests, changes in …

Support expose ports and add Google Cloud SDK image

---

.github/dependabot.yml

- Keep Github actions up-to-date via dependabot
- Allow more PRs to be opened

enable gh actions dependabot

---

src/clients/cli.rs
src/core.rs
src/core/image.rs
src/images/coblox_bitcoincore.rs
src/images/dynamodb_local.rs
src/images/elasticmq.rs
src/images/generic.rs
src/images/google_cloud_sdk.rs
src/images/hello_world.rs
src/images/kafka.rs
src/images/mongo.rs
src/images/orientdb.rs
src/images/parity_parity.rs
src/images/postgres.rs
src/images/redis.rs
src/images/trufflesuite_ganachecli.rs
src/images/zookeeper.rs
src/lib.rs

Attempt to resolve https://github.com/testcontainers/testcontainers-rs/pull/295#issuecomment-924628336 that also inspired me to further simplify a few things, which also includes addressing https://github.com/testcontainers/testcontainers-rs/pull/295#discussion_r700707178 
> Images that don't need arguments can just leave them as (). We can make our own trait to go from args -> string iterator so we can provide a default impl here.

Fix clippy warnings and simplify structs in images

---

src/images.rs
src/images/google_cloud_sdk_emulators.rs
tests/images.rs

To keep things lightweight, it is better to use the image that
has only the emulators and its dependencies. Also, included
support for Spanner emulator which was missed out earlier.

Use emulators tag for google cloud-sdk

---

CHANGELOG.md
Cargo.toml
src/images.rs
src/images/rabbitmq.rs
tests/rabbitmq.rs

Introduce an image for `RabbitMQ`.
It uses the `-management` tag so you also can use the management API in tests (e.g. to create VHosts).

Introduce RabbitMQ image

---

src/clients/cli.rs

This is simply a matter of only exposing ports if
the network does not start_with("container:").
Issue is https://github.com/testcontainers/testcontainers-rs/issues/319
Signed-off-by: Josh Hershberg <yehoshua@redis.com>

Support container networking

---

Cargo.toml
src/clients/cli.rs
src/clients/http.rs
src/core/container.rs
src/core/container_async.rs
src/core/ports.rs
tests/http_client.rs

Judging by the low activity in [shiplift](https://github.com/softprops/shiplift) (last commit on 1 Sep 2021, quite a few unmerged PRs after September and lack of response in the maintenance status clarification request softprops/shiplift#321), I think it's a good time to switch to a more actively maintained crate.
I picked Ballard because of the more active repo than `docker-api-rs`. And I liked the idea with the code generation from the API :)

Replace all Shiplift usages with Bollard

---

Cargo.toml

This PR aims to reduce the build time for the users who don't need the experimental features and don't need the bitcoincore image.

Refactor dependencies

---

.github/workflows/ci.yml
Cargo.toml

cargo officially allows key `rust-version` starting from Rust 1.56.0. In the older versions, the key will be ignored (though a warning will be displayed).
Having this value defined in Cargo.toml provides better visibility within the ecosystem. And it's just nicer to have this value specified in the config and not in a Github Workflow, even if reading it inside the workflow is a bit clunky :)

Add MSRV to Cargo.toml

---

src/core/image.rs
src/images/generic.rs

This PR fixes the errors reported by the nightly cargo: https://github.com/testcontainers/testcontainers-rs/runs/4847806082?check_suite_focus=true.
More info about the lint can be found here: https://rust-lang.github.io/rust-clippy/master/index.html#return_self_not_must_use.

Add #[must_use] for RunnableImage and GenericImage

---

src/clients/http.rs

Initially, I was trying to test if #271 was fixed after migrating to Bollard (and yes, it was!). I thought that the simplest way to test it is just run something like `docker run --rm ubuntu:latest bash -c 'sleep 10 && echo ready && sleep 10'`. It worked like a charm for the Cli client but started to fail as soon as I switched to the HTTP one. Long story short — #270 will be fixed with the changes in this PR, and #271 can already be closed.
You seem to just forget about the args when you were implementing the HTTP client :)
Fixes #270.

Add missed args passthrough in the HTTP client

---

CHANGELOG.md
src/clients/cli.rs
src/core/container_async.rs
src/core/image.rs

In this PR, I added the most naive and simple implementation for the `WaitFor::Healthcheck`. The ideal option will be to remove `delay` from the Enum. Still, the current implementation gives some flexibility to the users and eliminates the need of hardcoding the delay inside the crate.
As always, I'm open to suggestions :)
Fixes #321.

Add WaitFor::Healthcheck

---

CHANGELOG.md
Cargo.toml
src/images.rs
src/images/minio.rs
tests/images.rs

I think it should be pretty useful to have a `S3`-compatible default image.
Features:
- Specify server args via `MinIOServerArgs`
In addition, one test case was added.

Add MinIO image

---

README.md

The integration tests link in the README.md file is broken, update to the correct directory

Update integration tests link

---

testcontainers/src/clients/cli.rs

The implementations of `<Cli as Docker>::stdout_logs()` and `<Cli as Docker>::stderr_logs()` each invoke `docker logs -f <id>`, and capture one of stdout or stderr, for use in wait conditions. However, each method leaves one of the two streams from the `docker logs` process to follow the default behavior, `Stdio::inherit()`, which may result in container logs being printed to the TTY.
As an example, the postgres image prints to both stdout and stderr, and has a condition using `WaitFor::message_on_stderr()`. When this condition is checked, the container's stdout logs will be printed to the TTY.
This change adds redirection to the remaining streams in these two methods. With these changes, tests using the postgres container no longer print anything.

Suppress non-captured output from Cli::stdout_logs

---

CHANGELOG.md
testcontainers/Cargo.toml
testcontainers/src/clients/cli.rs
testcontainers/src/clients/http.rs
testcontainers/src/core/container.rs
testcontainers/src/core/container_async.rs
testcontainers/src/lib.rs
testcontainers/src/watchdog.rs

The watchdog will spawn a background thread that registers signal
handlers for SIGTERM, SIGINT, and SIGQUIT, if any such signal is
observed it will clean up currently running containers that are not
marked as `Keep`.
This fixes #364

Add `watchdog` feature to allow cleanup on kill

---

testcontainers/Cargo.toml

Upgrade bollard and bollard-stubs.
Because bollard 0.13 depends on an RC version of bollard-stubs we have to specify it exactly for Cargo (since Cargo won't pick an RC version when resolving, even if you put `^1` )

Upgrade bollard to 0.13 and bollard-stubs to 1.42.0-rc.3

---

testcontainers/src/clients/http.rs

Fix compilation errors encountered when running `cargo build --all-features`. 
Fixes #397 (see issue for more details on the encountered errors).

Fix errors when building with `--all-features`

---

testcontainers/src/clients/cli.rs
testcontainers/src/clients/http.rs
testcontainers/src/core/image.rs

Allow setting shared memory size (`--shm-size`) in bytes when creating an image.
Fixes #395.

Allow setting shared memory size

---

testcontainers/src/clients/cli.rs

Fix
```
error: the borrowed expression implements the required traits
--> testcontainers/src/clients/cli.rs:207:21
|
207 |         docker.args(&["network", "create", name]);
|                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: change this to: `["network", "create", name]`
|
= note: `-D clippy::needless-borrow` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
error: the borrowed expression implements the required traits
--> testcontainers/src/clients/cli.rs:217:21
|
217 |         docker.args(&["network", "ls", "--format", "{{.Name}}"]);
|                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: change this to: `["network", "ls", "--format", "{{.Name}}"]`
|
= help: for further …
```

Fix nightly lints

---

testcontainers/Cargo.toml
testcontainers/tests/dynamodb_local.rs
testcontainers/tests/elasticmq.rs
testcontainers/tests/images.rs
testcontainers/tests/minio.rs

This PR removes [Rusoto](https://github.com/rusoto/rusoto), which is currently in maintenance mode, from the Integration test examples and replaces it with [aws-sdk-rust](https://github.com/awslabs/aws-sdk-rust). The AWS Rust SDK is still in developer preview but is [tracking to GA](https://github.com/awslabs/smithy-rs/milestone/11) and has more recent active downloads than Rusoto.
Includes:
- removes `rusoto` in favour of `aws-sdk-rust`
- refactored integration tests for DynamoDB, SQS and S3 SDK clients
- separated test files for `MinIO`, `ElasticMQ` and `DynamoDB Local`

Replace rusoto with aws-sdk-rust in tests

---

CHANGELOG.md
testcontainers/src/clients/cli.rs
testcontainers/src/core/container.rs
testcontainers/src/core/image.rs

Closes #344
Remove of `-d` argument for `Container::exec` to ensure command has finished.
It's extremely useful when you need to ensure that command was executed as expected, but container logs can't tell this.
It also now returns output of command.
Any comments are welcome, that's quite straightforward way to implement it.

feat!: make `Container::exec` synchronous and return output

---

.github/workflows/ci.yml
bors.toml

The public bors instance is going away and GitHub now has a merge-queue feature in public beta.

Switch to GH merge queue from bors

---

testcontainers/src/clients/cli.rs

When container fails to start all you get is `failed to start container` message, and it's not always easy to guess why it failed. This PR includes command output in panic message.
Example:
`dev`:
> ```thread '<unnamed>' panicked at 'failed to start container'```
PR:
> ```thread '<unnamed>' panicked at 'failed to start container, output = Output { status:  ExitStatus(unix_wait_status(32000)), stdout: "e5866b9407496bc9a88b63528370de91ec43358a6a40e1262fb3cae9dd3a8ec1\n", stderr: "docker: Error response from daemon: driver failed programming external connectivity on endpoint dazzling_elbakyan (85503e92065801ce10c86a95ba9af00c53e0e9a3ec4eb0ad78e55e306fbf8434): Bind for 0.0.0.0:13306 failed: port is already allocated.\n" }'```

Log error when starting a container fails

---

README.md
testcontainers/src/lib.rs

It would be nice to mention the new location of ready-to-use images, because of https://github.com/testcontainers/testcontainers-rs/issues/471
It will helpful for users once `0.15.0` is released.

docs: mention `testcontainers-modules`

---

testcontainers/src/core/env.rs

`Nightly / nightly-lints` failing because of this

style: derive `Default` to fix clippy lint

---

testcontainers/Cargo.toml
testcontainers/src/clients/cli.rs
testcontainers/src/clients/http.rs

`spectral` is outdated (last update >7 years ago), it causes warning:
```
the following packages contain code that will be rejected by a future version of Rust: rustc-serialize v0.3.24
```
And actually there is no need in it

chore(deps): remove `spectral` from `dev-dependencies`

---

testcontainers/src/clients/cli.rs
testcontainers/src/core.rs
testcontainers/src/core/image.rs
testcontainers/tests/cli_client.rs

When spawning multiple docker containers in the same test, communication amongst them can be achieved over the docker default gateway.
In DinD environments, such as when running jobs on a CI pipeline, the docker [`--add-host`](https://docs.docker.com/engine/reference/commandline/container_run/#option) can be employed to basically enter new entries in the `/etc/hosts` files. This allows to avoid binding all container ports to the host environment.
The flag API counterpart is implemented on the `RunnableImage` struct instead of on the generic image since I reckon it makes more sense within this crate phylosophy, I hope !-).
A test runs 2 containers:
- an http_server
- a `curl` client
and the `curl` client completes when receiving `foo` from the server on the alias hostname. In case the …

feat(cli): support for docker cli flag `--add-host`

---

.github/workflows/ci.yml

Use cargo-hack instead of matrix to minimize number of GH jobs and make it more comprehensive (each feature is tested)

build(ci): update msrv check

---

CONTRIBUTING.md
README.md

Inside of the Matrix channel, it is mentioned that the official contact channel is now Slack.

docs: change old contact link to the Slack one

---

CHANGELOG.md
testcontainers/src/core/image.rs

This change allows to override name of the image. Thus, user will be able to change registry, owner and the name itself.
See https://github.com/testcontainers/testcontainers-rs/issues/335#issuecomment-1951399972 for more details
Closes https://github.com/testcontainers/testcontainers-rs/issues/335

feat: add `name` parameter to `RunnableImage`

---

testcontainers/Cargo.toml
testcontainers/src/core.rs
testcontainers/src/core/image.rs
testcontainers/src/core/image/exec_command.rs
testcontainers/src/core/image/runnable_image.rs
testcontainers/src/core/image/wait_for.rs
testcontainers/src/core/mounts.rs
testcontainers/src/images/generic.rs
testcontainers/src/runners/async_runner.rs
testcontainers/src/runners/sync_runner.rs

Closes #582
This is breaking change.
The API was unclear, because `volumes` used to mean `bind-mounts`, which is wrong.
Introduce `Mount` structure with the following mount types:
- bind
- volume
- tmpfs
Also exposes access-mode configuration for mounts: `rw` (read-write) and `ro` (read-only)
*Note*: named volumes not getting removed once container is removed, it's intentional for now. Because named volumes can be used to persist a state. We can review this point later.
- If your `Image` implements `volumes` method:
- rename method to `mounts`
- wrap all existed "volumes" into `Mount::bind_mount(host_path, container_path)`
- If your code uses `RunnableImage::with_volume`
- replace the call with `RunnableImage::with_mount`
- If your code uses `GenericImage::with_volume`
- replace the call …

refactor!: api for mounts and volumes

---

testcontainers/src/core.rs

They supposed to be public, but module has crate-visibility

fix: expose mount-related types

---

testcontainers/Cargo.toml
testcontainers/src/core/env/config.rs
testcontainers/src/lib.rs

To avoid extra dependencies, expose the logic for reading java-properties file only under the feature
Technically it's breaking change, but we don't expect a lot of usage since this feature was introduced very recently and not that common for rust community

feat: introduce `properties-config` cargo feature

---

testcontainers/src/runners/async_runner.rs

We shouldn't auto-map exposed ports as part of port bindings if there are explicit mappings. Otherwise we use `publish_all_ports` option.
However, we should auto-expose mapped ports if Image impl doesn't. Because it's a way to override the behavior with `RunnableImage`.

fix: properly expose mapped ports

---

testcontainers/src/core/client.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/runners/sync_runner.rs

`IpAddr` can't be parsed from `localhost`, it expects domain.
We could use `url::Host`, but it would be a breaking change and method must be renamed in that case

fix: correct default for `get_host_ip_address` in case of `unix` or `npipe`

---

testcontainers/Cargo.toml
testcontainers/src/core/client.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/containers/sync_container.rs
testcontainers/tests/sync_runner.rs

Existing logic is incorrect, because we may encounter domain name.
Also, `IpAddr` isn't suitable for URL usage (because of `IpV6`).
`url::Host` is better alternative and supports:
- Domain names
- escapes `IpV6` for `URL`
We preserve `get_host_ip_address` for now, but we have to get rid of this method and extra dependency in the next major release

feat: add `get_host` to `Container` and deprecate `get_host_ip_address`

---

testcontainers/src/core.rs
testcontainers/src/core/image.rs
testcontainers/src/core/image/runnable_image.rs
testcontainers/src/lib.rs
testcontainers/src/runners/async_runner.rs

Allow cgroupns and userns to be defined when building RunnableImage

feat: allow cgroupns-mode and userns-mode to be configured 

---

testcontainers/src/core/client.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/containers/sync_container.rs

The implementation should be aligned with this impl: https://github.com/testcontainers/testcontainers-java/blob/994b385761dde7d832ab7b6c10bc62747fe4b340/core/src/main/java/org/testcontainers/dockerclient/DockerClientProviderStrategy.java#L451-L467
I.e. we should return `Gateway` only if client running in a container.
Otherwise, it's `localhost` for `unix` and `pipe`

fix: `get_host` for `unix` and `npipe` docker hosts

---

testcontainers/src/core.rs
testcontainers/src/core/client.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/image.rs
testcontainers/src/core/image/exec_command.rs
testcontainers/src/core/logs.rs
testcontainers/tests/async_runner.rs
testcontainers/tests/sync_runner.rs

- support check of exit code
- allow check the message against both `stderr` and `stdout`
- extend `new` to accept `impl IntoIterator<Item = impl Into<String>>` (e.g to accept `["cmd", "arg1", "arg2"]` as is)
Closes #617

feat: extend `WaitFor` for `ExecCommand`

---

testcontainers/Cargo.toml
testcontainers/src/core/logs.rs

- improves error/panic message
- we're going to introduce fallible API gradually, so we can consider this as a first step 
- it solves the issue of unused fields, because debug impl is intentionally ignored by the dead_code lint

feat: impl `Error` for `WaitError`

---

testcontainers/src/lib.rs
testcontainers/src/runners/async_runner.rs

`CgroupnsMode` is accessible through `testcontainers::core::CgroupnsMode`, there is no need to re-export it on crate-level, it's not that common config and there is no high-demand on this.
Usually, only high-level structures are re-exported.
But I would like to consider improving the structure of our modules in the future.

refactor!: drop re-export of `CgroupnsMode` accessible through `core`

---

.github/workflows/ci.yml
testcontainers/src/core/client.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/runners/async_runner.rs
testcontainers/src/runners/sync_runner.rs

I bumped into this issue while using https://github.com/testcontainers/testcontainers-rs-modules-community/tree/main/src/mysql 
and the latest version of testcontainers-rs.
`get_bridge_ip_address` was not returning the correct IP address value. When running a container on GNU/Linux systems
`NetworkSettings.bridge` might be an empty string therefore it is not useful as a default value.
This PR tries to provide a default value for such scenarios where:
- No `--bridge` flag has been explicitly provided when starting the container
- `NetworkSettings.bridge` is an empty string
- Container has not been launched with a specific network and therefore defaults to whatever is configured on the docker daemon
Thanks for all the efforts in this project!

fix: collect bridge IP address correctly

---

CHANGELOG.md
testcontainers/Cargo.toml
testcontainers/src/core.rs
testcontainers/src/core/client.rs
testcontainers/src/core/client/exec.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/containers/async_container/exec.rs
testcontainers/src/core/containers/mod.rs
testcontainers/src/core/containers/sync_container.rs
testcontainers/src/core/containers/sync_container/exec.rs
testcontainers/src/core/errors.rs
testcontainers/src/core/image.rs
testcontainers/src/core/image/exec.rs
testcontainers/src/core/image/wait_for.rs
testcontainers/src/core/logs.rs
testcontainers/src/lib.rs
testcontainers/src/runners/async_runner.rs
testcontainers/src/runners/sync_runner.rs
testcontainers/tests/async_runner.rs
testcontainers/tests/sync_runner.rs

Closes #617
Step towards #502 and #606
Additionally:
- Support non-utf8 logs.

feat!: extend `exec` interface to return logs and exec code

---

testcontainers/Cargo.toml
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/containers/async_container/exec.rs
testcontainers/src/core/containers/sync_container.rs
testcontainers/src/core/containers/sync_container/exec.rs
testcontainers/src/core/containers/sync_container/sync_reader.rs
testcontainers/tests/async_runner.rs
testcontainers/tests/sync_runner.rs

Closes #502
Exposes `stdout` and `stderr` methods, which returns:
- `tokio::io::AsyncBufRead` impl for async container
- `std::io::BufRead` impl for sync container (under `blocking` feature)
Also, small alignment is performed (related to #617):
- rename the `ExecResult` `stdout`/`stderr` methods to match the container methods

feat: ability to access container logs

---

testcontainers/src/core/client.rs
testcontainers/src/core/client/exec.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/containers/async_container/exec.rs
testcontainers/src/core/containers/sync_container.rs
testcontainers/src/core/containers/sync_container/exec.rs
testcontainers/src/core/containers/sync_container/sync_reader.rs
testcontainers/src/core/logs.rs

There is no need to stick logs to lifetime of container:
- this way logs can't be sent to another thread/task
- logs will stop with EOF if container has been dropped anyway, what's reasonable
- it's step forward log followers (like in [Java implementation](https://java.testcontainers.org/features/container_logs/))

feat: make container and exec logs `Send`able

---

testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/containers/async_container/exec.rs
testcontainers/src/core/containers/sync_container.rs
testcontainers/src/core/containers/sync_container/exec.rs

It allows to read logs only until the moment of the call (i.e read all currently accessible logs)

feat: expose follow flag for `stdout` and `stderr`

---

testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/containers/async_container/exec.rs
testcontainers/src/core/containers/sync_container.rs

We already have these methods for `exec`, they are good shortcuts, and I added them to `Container` as well to make the interfaces consistent.

feat: add ability to read container logs into `Vec`

---

testcontainers/src/core/error.rs
testcontainers/src/core/image/runnable_image.rs
testcontainers/src/runners/async_runner.rs

Closes #247
- Sets default startup timeout to 1 minute
- Allows to override with `RunnableImage::with_startup_timeout`
Note: breaking change because of default timeout
For now, ENV variable to configure global timeout isn't introduced. First of all, that's quote similar to other languages, (e.g [Go](https://golang.testcontainers.org/features/wait/introduction/#startup-timeout-and-poll-interval), [Java](https://java.testcontainers.org/features/startup_and_waits/))
Another question is which one should take precedence: ENV over `with_startup_timeout` or vice versa?
We can extend it later in compatible way, so not that important at the moment.

feat!: add container startup timeout with default of 1 minute

---

testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/image.rs
testcontainers/src/runners/async_runner.rs

That's much easier for users to use `?` in `exec_after_start` instead of mapping manually to appropriate error.

refactor!: return `PortNotExposed` error from `ContainerState::host_port_*`

---

docs/features/configuration.md
docs/features/wait/introduction.md
docs/features/wait_strategies.md
docs/index.md
docs/quickstart/community_modules.md
docs/quickstart/testcontainers.md
mkdocs.yml

Add quick-start guides and some basic documentation from `docs.rs` (e.g configuration, wait strategies).
We still need to cover a lot of topics to make it more visible, but let's do it iteratively!

docs: add quickstarts and replicate docs.rs info to website

---

Cargo.toml

It's really helpful and allows some further refactoring for better API.
In most of the cases, it should not be a problem (and even pretty common) to run test against fresher versions of Rust.
PR is needed for https://github.com/testcontainers/testcontainers-rs/pull/649 and couple of follow-up PRs

chore!: bump MSRV to `1.75` to allow `RPIT` & `AFIT`

---

README.md
testcontainers/src/core.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/containers/sync_container.rs
testcontainers/src/core/image.rs
testcontainers/src/core/image/runnable_image.rs
testcontainers/src/images/generic.rs
testcontainers/src/lib.rs
testcontainers/src/runners/async_runner.rs
testcontainers/src/runners/sync_runner.rs
testcontainers/tests/async_runner.rs
testcontainers/tests/sync_runner.rs

- really common pattern is to use `Vec<String>`
- `args` isn't the best term, because in fact it's Docker's [CMD](https://docs.docker.com/reference/dockerfile/#cmd)
- it was not aligned with existing `ExecCommand`
- current interface is confusing and users struggle with it
- essentially it should be closer to the current representation of environment variables and other parameters
- new implementation allows to override args regardless of underlying type
- it's still will be possible to use custom strict arguments type for particular image which can be converted to list of strings if users want
Dependent PR to modules: https://github.com/testcontainers/testcontainers-rs-modules-community/pull/143
Also, I'm preparing 2 follow-up PRs which will improve the user experience.

refactor!: get rid of associated type `ImageArgs` and rename to `cmd`

---

testcontainers/Cargo.toml
testcontainers/src/core/containers/sync_container.rs
testcontainers/src/core/image.rs
testcontainers/src/core/image/runnable_image.rs
testcontainers/src/images/generic.rs
testcontainers/src/runners/async_runner.rs
testcontainers/src/runners/sync_runner.rs
testcontainers/tests/async_runner.rs
testcontainers/tests/sync_runner.rs

It's quite big incompatible change, but in general it doesn't require a lot of work to switch to new API.
And it will be mostly transparent for users of [ready-to-use modules](https://github.com/testcontainers/testcontainers-rs-modules-community/pull/144)
- get rid of `Box<dyn Iterator<..>`, use RPIT instead
- use `Into<Cow<'_, str>` instead of `&String`
- use `&str` instead of `String`
In fact, we don't need owned structs from image methods, and even if we need - it's better to cast implicitly under the hood, avoiding extra cloning in every image implementation.
Also, a new API relaxes requirements of returned type and makes some use-cases simpler.

refactor(image): avoid unnecessary owned structs and boxing

---

docs/quickstart/community_modules.md
testcontainers/src/core.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/containers/sync_container.rs
testcontainers/src/core/image.rs
testcontainers/src/core/image/image_ext.rs
testcontainers/src/core/image/runnable_image.rs
testcontainers/src/images/generic.rs
testcontainers/src/lib.rs
testcontainers/src/runners/async_runner.rs
testcontainers/src/runners/sync_runner.rs
testcontainers/tests/async_runner.rs
testcontainers/tests/sync_runner.rs

This PR allows to override some image values without explicit conversion to `RunnableImage`.
For example:
```rs
// Instead of this:
use testcontainers::RunnableImage;
RunnableImage::from(image).with_tag("x").with_network("a").start();
// It can be done directly on image:
use testcontainers::ImageExt;
image.with_tag("x").with_network("a").start();
```
Also, it allows to simplify `GenericImage`. Because it was kinda duplicative code.

refactor!: add `ImageExt` trait to avoid explicit conversion to `RunnableImage`

---

docs/features/wait_strategies.md
docs/quickstart/community_modules.md
testcontainers/src/core.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/containers/mod.rs
testcontainers/src/core/containers/request.rs
testcontainers/src/core/image.rs
testcontainers/src/core/image/image_ext.rs
testcontainers/src/lib.rs
testcontainers/src/runners/async_runner.rs
testcontainers/src/runners/sync_runner.rs

I decided to go with renaming because it's a good moment: we've provided `ImageExt` trait in order to avoid direct usage of `RunnableImage` when possible. Renaming seems to be minor issue in contrast of other changes.
This is semantically more correct, it allows to customize some parameters of a container to create, but not the image itself (`network`, `shm_size`, `cgroupns` etc.). Subjectively, it's more obvious to see  `ContainerRequest<Redis>` instead of `RunnableImage<Redis>`. Also, it's similar to Testcontainers for Go.

refactor!: rename `RunnableImage` to `ContainerRequest`

---

docs/features/configuration.md
testcontainers/src/core/env/config.rs
testcontainers/src/lib.rs

`DOCKER_CONFIG` typically points to the directory with config files, and the actual configuration file is usually expected at `${DOCKER_CONFIG}/config.json`:
- Docker CLI https://docs.docker.com/engine/reference/commandline/cli/#environment-variables
- testcontainers-java https://github.com/testcontainers/testcontainers-java/blob/6658a2c0a880d01c6d402ea9a4cb5f72eb15083c/core/src/main/java/org/testcontainers/utility/RegistryAuthLocator.java#L78-L81
testcontainers-rs treats this variable differently as a path to the configuration file (it does not append `/config.json`), so when the environment is configured to be used by other docker-related tools, testcontainers-rs fails to read the configuration, thus failing to access private registries.
This pull request makes `DOCKER_CONFIG` variable …

fix!: make `DOCKER_CONFIG` usage consistent with Docker CLI

---

testcontainers/src/core.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/containers/request.rs
testcontainers/src/core/containers/sync_container.rs
testcontainers/src/core/error.rs
testcontainers/src/core/image.rs
testcontainers/src/core/image/image_ext.rs
testcontainers/src/core/ports.rs
testcontainers/src/images/generic.rs
testcontainers/src/runners/async_runner.rs
testcontainers/src/runners/sync_runner.rs
testcontainers/tests/dual_stack_host_ports.rs
testcontainers/tests/sync_runner.rs

Follow-up PR after #655 (kudos to @estigma88 :tada: )
- rename `ExposedPort` to `ContainerPort`
- minor internal renaming to align terminology
- `with_mapped_port`: accept two arguments  instead of tuple
- introduce `IntoContainerPort` to make a shortcut for conversion from `u16` to `ContainerPort`

refactor!: exposed and mapped ports api

---

testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/containers/sync_container.rs
testcontainers/src/core/ports.rs
testcontainers/src/runners/async_runner.rs

As a result, it was decided that such a default makes sense - it corresponds to the default behavior of Docker, and is also more common use case.

feat: impl `From<u16>` for `ContainerPort` with TCP default

---

testcontainers/Cargo.toml
testcontainers/src/core.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/error.rs
testcontainers/src/core/image.rs
testcontainers/src/core/image/exec.rs
testcontainers/src/core/wait/cmd_wait.rs
testcontainers/src/core/wait/http_strategy.rs
testcontainers/src/core/wait/mod.rs
testcontainers/tests/async_runner.rs
testcontainers/tests/sync_runner.rs

Introduces HTTP wait strategy
Closes #648 
Additional documentation in follow-up PR

feat: support HTTP wait strategy

---

testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/wait/health_strategy.rs
testcontainers/src/core/wait/http_strategy.rs
testcontainers/src/core/wait/mod.rs

Split implementation into separate strategies.
Also, this PR allows to customize healthcheck polling interval
Later, we will need to:
- introduce log-followers and switch log wait strategy to it, using channels and avoiding multiple log reads.
-

refactor: preliminary refactoring of `wait` strategies

---

testcontainers/src/core/ports.rs

Add `as_u16` method to `ContainerPort`

feat: add ability to convert `ContainerPort` to `u16`

---

testcontainers/src/core/containers/sync_container.rs
testcontainers/src/runners/sync_runner.rs

We need this to support log-consumers/followers, since it requires the spawned tasks to run regardless of the `block_on` call.

refactor: use multi-threaded runtime for blocking feature

---

testcontainers/Cargo.toml
testcontainers/src/core/wait/http_strategy.rs

Closes #671 
`reqwest` exposes a number of TLS-related features, there is no much sense to re-expose them.
Cargo features are additive (and reqwest follows this rule), so it's always possible to customize by adding `reqwest` dependency with desired feature-set
We can re-consider feature-set provided by `testcontainers` later, but currently we already depend on them through `bollard`: it relies on `rustls` and `rustls-native-certs`
It's even possible to make these features optional (e.g when you don't need tls support neither for docker nor reqwest).

fix!: use `rustls-tls` as default for `reqwest`

---

testcontainers/Cargo.toml
testcontainers/src/core.rs
testcontainers/src/core/client.rs
testcontainers/src/core/client/exec.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/logs.rs
testcontainers/src/core/logs/stream.rs
testcontainers/src/core/wait/mod.rs

Preliminary refactoring to clean up the code and prepare the code-base before introducing log consumers.

refactor: internal log processing structures

---

testcontainers/src/core/containers/request.rs

`Image` can be cloned just fine, but `ContainerRequest` is not intended to be, and is not, a truly safe structure for cloning. It allows to override unique container properties: container name, port mappings and log consumers (soon).
If necessary, you can always use a reusable constructor/method to create multiple similar `ContainerRequests`.

fix!: drop `Clone` impl for `ContainerRequest`

---

testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/image.rs
testcontainers/src/core/logs.rs
testcontainers/src/core/wait/log_strategy.rs
testcontainers/src/core/wait/mod.rs
testcontainers/tests/async_runner.rs
testcontainers/tests/sync_runner.rs
testimages/src/bin/simple_web_server.rs

The interface has been changed a bit to support advanced configuration of the strategy. For example, to wait for a message to appear twice in `stdout`:
```rs
WaitFor::log(
LogWaitStrategy::stdout("server is ready").with_times(2),
)
```
Closes #675

feat(wait)!: enhance `LogWaitStrategy` to wait for message appearance multiple times

---

testcontainers/src/core/containers/async_container.rs

The error might be expected, e.g. container has been stopped.

chore: relax log level for log producer error

---

testcontainers/src/runners/async_runner.rs

The main purpose of this timeout is to ensure that the wait strategies do not get stuck. But image pulling should not be timed out. 
If necessary, users can always use a external timeout or explicit [pull_image](https://docs.rs/testcontainers/latest/testcontainers/runners/trait.AsyncRunner.html#tymethod.pull_image) call

fix: exclude image pulling time from startup timeout

---

testcontainers/src/core/logs.rs
testcontainers/src/core/wait/mod.rs
testcontainers/tests/async_runner.rs
testimages/src/bin/simple_web_server.rs

There was a mistake in `WaitFor::message_on_stderr`. Covered with simple test now.

fix: pass correct log-source for `stderr` wait strategy

---

testcontainers/src/core/client.rs
testcontainers/src/core/client/bollard_client.rs
testcontainers/src/core/env/config.rs
testcontainers/src/runners/async_runner.rs
testcontainers/tests/async_runner.rs

This is one way to fix https://github.com/testcontainers/testcontainers-rs/issues/708
Although we still parse into a `Url`, we don't pass that value on to clients, since `Url` may mutate the input, which in the case of #708, breaks Windows `NamedPipeConnector`, which is the default way of connecting to the Docker daemon.
I also disabled the SCTP tests on Windows since it doesn't seem there's support for that on Windows.

fix: don't assume docker host is a url

---

testcontainers/src/core/containers/request.rs
testcontainers/src/core/image/image_ext.rs
testcontainers/src/runners/async_runner.rs
testcontainers/src/runners/sync_runner.rs

Thanks again for working on this project!
This exposes a way to configure resource ulimits (the [`--ulimit`](https://docs.docker.com/reference/cli/docker/container/run/#ulimit) flag for `docker run`).
I'm relying on CI tests because I'm currently on Windows and didn't configure my environment to reflect https://github.com/testcontainers/testcontainers-rs/issues/711, since it seems I'd need to install nasm now, as I received some errors regarding it.

feat: allow configuring resource ulimits

---

testcontainers/src/lib.rs

The motivation is to make [`cargo-geiger`](https://github.com/geiger-rs/cargo-geiger) be sure that there is no unsafe code

chore: add `#![forbid(unsafe_code)]` to the library

---

docs/quickstart/community_modules.md

The required feature for postgres support is "postgres" and not "posrges".

docs: fix typo in community_modules.md

---

testcontainers/src/core/containers/request.rs
testcontainers/src/core/image/image_ext.rs
testcontainers/src/runners/async_runner.rs

Implements #720 by adding support for setting the working directory on `ImageExt` and `ContainerRequest`. Also adds a test for this feature. This is equivalent to the `-w, --workdir` flag of `docker run`.
The abbreviation `working_dir` (as opposed to e.g. `working_directory`) was chosen to use the same name as the `bollard` crate.

feat: add `working_dir` to `ContainerRequest`,`ImageExt`

---

testcontainers/src/core/client.rs
testcontainers/src/core/client/bollard_client.rs
testcontainers/src/core/env/config.rs
testcontainers/src/lib.rs

Docker Desktop on macOS creates the socket in the user's home directory from version 4.13.0.[[1](https://github.com/docker/for-mac/issues/6529)][[2](https://github.com/testcontainers/testcontainers-java/issues/6165)]
And the Docker team [has the intention to move away](https://github.com/docker/for-mac/issues/6529#issuecomment-1710091807) from the root-owned `/var/run/docker.sock`
There is a option named `Allow the default Docket Socket to be used (requires password)` in the Docker Desktop, but the created symbolic link `/var/run/docker.sock` [doesn't persist](https://github.com/lando/lando/issues/3533#issuecomment-1464252377) between OS restart or OS upgrade.
Without this patch or creating a symbolic link, macOS devs have to face the ```called `Result::unwrap()` on an `Err` value: …
```

fix: docker socket detection on unix

---

CONTRIBUTING.md
testcontainers/Cargo.toml
testcontainers/src/core.rs
testcontainers/src/core/client.rs
testcontainers/src/core/containers/request.rs
testcontainers/src/core/copy.rs
testcontainers/src/core/image.rs
testcontainers/src/core/image/image_ext.rs
testcontainers/src/lib.rs
testcontainers/src/runners/async_runner.rs
testcontainers/tests/async_runner.rs
testcontainers/tests/sync_runner.rs

This PR supports copying files into the container like this:
```rust
let container = GenericImage::new("alpine", "latest")
.with_wait_for(WaitFor::seconds(2))
.with_copy_to("/tmp/somefile", "foobar".to_string().into_bytes())
.start()
.await?;
```

feat: support copy files to container

---

testcontainers/src/core/copy.rs
testcontainers/src/core/image/image_ext.rs
testcontainers/src/runners/async_runner.rs
testcontainers/tests/async_runner.rs
testcontainers/tests/sync_runner.rs

Small improvements to encapsulate some parts of new functionality in order to reduce a chance of breaking changes in the future

chore: copy-to-container interface improvements

---

testcontainers/src/lib.rs

Public types should be usable.

fix: expose public `copy` types

---

testcontainers/Cargo.toml
testcontainers/src/core/env/config.rs

I recently learned that [`dirs`](https://crates.io/crates/dirs) depends on [`option-ext`](https://crates.io/crates/option-ext) via [`dir-sys`](https://crates.io/crates/dirs-sys) (as of `dir-sys` 0.4.1 that came in as part of `dirs` 5.0.1), which is MPL 2.0 licensed.
[It does not appear that the author is interested reconsidering their stance on licensing](https://github.com/dirs-dev/dirs-sys-rs/issues/21#issuecomment-1531528155), which unfortunately creates some complications for projects under the CNCF umbrella (as well as many corporate projects), and so I thought I would propose switching `dirs` out for `etcetera` since it is MIT or Apache 2.0 licensed.
As you can see from the linked thread, this is a fairly common limitation for adoption, so in the interest of enabling further …

refactor: replace dirs crate with etcetera

---

testcontainers/src/core.rs
testcontainers/src/core/client.rs
testcontainers/src/core/client/factory.rs

This PR allows to access bollard client directly if needed. It's aligned with implementations of testcontainers for other languages. Definitely may be useful in some specific cases and allows to bypass some limitations. We could wrap and expose only particular API methods and hide the details from the user, but it's too much work and this way seems more pragmatic.
Later we also can re-export bollard and bollard_stubs on demand (in order to simplify version managment of deps for users)

feat: expose configured bollard client

---

docs/quickstart/testcontainers.md

docs(quickstart): make the first example runnable

---

README.md
testcontainers/src/images/generic.rs

I struggled a bit when upgrading to testcontainers-rs 0.23, since the interfaces had changed somewhat since the last version I used. The documentation didn't explain exactly how to use the methods in `ImageExt` in conjunction with those of `GenericImage`.
This change adds a bit more content to the documentation:
* A few more lines in the README file to exercise the configuration methods in `ImageExt`,
* Some documentation for `GenericImage` showing how it is used along with `ImageExt`.
The latter in particular includes a doctest. If the API is changed in the future so that further changes are needed, the doctest will fail and can be updated accordingly. This will make it easier for downstream users to understand how to port their code.

docs: add examples of `ImageExt` usage and cover `GenericImage`

---

README.md

The message inside the expect is shown on failure, so updated the example to reflect that

docs: negative failure message instead of a postive one

---

testcontainers/tests/async_runner.rs

The test often fails, especially in GitHub actions. The test attempts to start four containers on the same image and sets a deadline to prove that they start in parallel rather than in serial. The failure messages indicate tha this deadline is exceeded.
This appears to happen when the image of the container being started has to be pulled. Sometimes the pull operation takes so much time that the deadline is exceeded just due to that.
This adds some lines to the test which start and then stop a container on the same image before attempting to start the containers in parallel. Doing so ensures that the image has already been pulled when the real test starts running. Then the containers should start in close to the intended two seconds, so the test should pass more reliably.
Manual …

test: deflake the test `start_containers_in_parallel`

---

testcontainers/src/core/containers/request.rs
testcontainers/src/core/image/image_ext.rs
testcontainers/src/runners/async_runner.rs

Hi :wave: This PR implements #578 and adds tests for the added functionality.
Specifically, this PR adds support for adding and dropping capabilities for containers.
Have a nice weekend!

feat: add `cap_add` and `cap_drop` support

---

testcontainers/src/core/containers/request.rs
testcontainers/src/core/image/image_ext.rs
testcontainers/src/runners/async_runner.rs

PR adds support for applying user-configured labels to containers started by `testcontainers`.
> [!NOTE]
> This PR is a precursor to future support of [reusable containers](https://github.com/testcontainers/testcontainers-rs/issues/742)

feat: add support for user-configured labels

---

.github/workflows/ci.yml
testcontainers/Cargo.toml
testcontainers/src/core.rs
testcontainers/src/core/client.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/containers/request.rs
testcontainers/src/core/image.rs
testcontainers/src/core/image/image_ext.rs
testcontainers/src/lib.rs
testcontainers/src/runners/async_runner.rs

PR implements reusable containers inline with [the existing](https://java.testcontainers.org/features/reuse/) reusable containers feature(s) of `testcontainers` for other languages.
> [!IMPORTANT]
> This PR follows from (and is branched from) #756. PR 756 *must* be merged prior to merging this PR

feat: reusable containers

---

docs/features/exec_commands.md
docs/system_requirements/docker.md
mkdocs.yml
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/wait/cmd_wait.rs
testcontainers/tests/async_runner.rs
testcontainers/tests/sync_runner.rs

It was possible via explicit error handling in the client code, but it's a nice shortcut
Closes https://github.com/testcontainers/testcontainers-rs/issues/744

feat: support waiting for commands exit regardless of exit code

---

.github/workflows/ci.yml
docs/features/configuration.md
testcontainers/Cargo.toml

In order for consumers to be able to switch between `ring` and `aws-lc-rs` cleanly without `testcontainers_rs` bringing in the wrong library, add feature flags that are propagated through to `bollard` to switch between the two ssl providers.

build: propagate ring/aws-lc-rs feature flags to bollard

---

testcontainers/src/core/containers/request.rs
testcontainers/src/core/image/image_ext.rs
testcontainers/src/runners/async_runner.rs

This was inspired by https://github.com/testcontainers/testcontainers-rs/issues/762 and my project's requirement to use an image that requires running with root user inside the container.
This pull request introduces the ability to configure a user that commands are run as inside a container in the `testcontainers` library. The most important changes include adding a new `user` field to the `ContainerRequest` struct, implementing methods to set and retrieve the user, and updating relevant tests to ensure this functionality works correctly.
Enhancements to `ContainerRequest`:
* [`testcontainers/src/core/containers/request.rs`](diffhunk://#diff-450493263e745439645d3062a1defe3bdedcadacabb123fe7664244e42570049R46): Added a new `user` field to the `ContainerRequest` struct and provided a …

feat: add user configuration for container commands

---

testcontainers/src/core/client.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/containers/sync_container.rs
testcontainers/src/core/logs/consumer/logging_consumer.rs
testcontainers/src/core/logs/stream.rs
testcontainers/src/core/wait/mod.rs
testcontainers/src/runners/async_runner.rs
testcontainers/src/watchdog.rs

Previously containers were stopped with no timeout (SIGKILL) which was interfering with clean shutdown of processes being tested. 
This commit adds a new API of stop_with_timeout(timeout_secconds) in addition to the original stop(). The original stop() interface calls stop_with_timeout using the default '0'.
EDIT:
It would seem my original diagnosis was incorrect and the default timeout is 10 seconds, but my CI system was somehow setting the default to 1 second. I will fix the docs and put in the correct default. I think there is still some value in here - apologies for the time waste getting to this point!

feat: add option to stop containers with a timeout

---

testcontainers/src/core/client.rs
testcontainers/src/core/containers/async_container.rs
testcontainers/src/core/containers/sync_container.rs

This adds the pause/unpause calls for ContainerAsync/Container because I wanted to have an integration test keeping the same port for a mosquitto container.
fixes #715, #433

feat: support `pause` and `unpause` container

---

testcontainers/src/core/containers/request.rs
testcontainers/src/core/image/image_ext.rs
testcontainers/src/runners/async_runner.rs

I want to implement a Talos test container, and there is no way to change some arguments.
```
docker run --rm -it \
--name tutorial \
--hostname talos-cp \
--read-only \
--privileged \
--security-opt seccomp=unconfined \
--mount type=tmpfs,destination=/run \
--mount type=tmpfs,destination=/system \
--mount type=tmpfs,destination=/tmp \
--mount type=volume,destination=/system/state \
--mount type=volume,destination=/var \
--mount type=volume,destination=/etc/cni \
--mount type=volume,destination=/etc/kubernetes \
--mount type=volume,destination=/usr/libexec/kubernetes \
--mount type=volume,destination=/opt \
-e PLATFORM=container \
ghcr.io/siderolabs/talos:v1.9.5
```

feat: allow `security_opt` and `readonly_rootfs` to be configured

---

testcontainers/src/core/client.rs
testcontainers/src/core/logs.rs
testcontainers/src/core/logs/stream.rs
testcontainers/src/core/wait/log_strategy.rs
testcontainers/src/core/wait/mod.rs

This PR introduces part of changes proposed in #793.
I am not sure about naming of new methods and LogStrategy, I don't like current but was unable to come up with something better.

feat: allow to wait for log line on either stdout or stderr

---

.github/workflows/ci.yml
testcontainers/src/core/client/bollard_client.rs

Allows to disable TLS features (with `default-features=false`)
`ring` still enabled by default
Closes #799

fix: make tls features optional

---

testcontainers/src/core/ports.rs

Also edited corresponding test.
**It would be great if you could merge it into the 24 release.**
After update of docker  from `27.5.1` to `28.3.0, build 38b7060` error related to port parsing occured. Specifically port parsing fails on port without protocol specifier.
Maybe this [issue](https://github.com/moby/moby/issues/45199) will help clarify things.
Here is `docker inspect` on running `scylladb/scylla:6.0` docker container, created with testcontainers api using different version of docker.
```
"Ports": {
"10000/tcp": [
{
"HostIp": "0.0.0.0",
"HostPort": "55062"
}
],
"22/tcp": [
{
"HostIp": "0.0.0.0",
"HostPort": "55056"
}
]
}
```
```
"Ports": {
"10000": [],
"10000/tcp": [
{
"HostIp": "0.0.0.0",
"HostPort": "55475"
}
],
"22": [],
"22/tcp": [
{
"HostIp": "0.0.0.0",
"HostPort": "55469" …
```

fix: added new parse rule for correctly parsing ports without protocol specifier

---

release-plz.toml

The introduction of the builder-API removed the `testimages` package.

ci: adapt release-plz configuration

---

Cargo.toml

Extracted from https://github.com/testcontainers/testcontainers-rs/pull/828

chore: update MSRV from 1.82 to 1.86

---

.github/workflows/ci.yml
testcontainers/Cargo.toml
testcontainers/src/core/containers/request.rs
testcontainers/src/core/image/image_ext.rs
testcontainers/src/runners/async_runner.rs

This should expose the Bollard API to make device requests and enable usage of host's GPUs for tests.
I didn't find a good way to integrate with CI since the test I wrote depends on an actual GPU. I wrapped the feature on a feature flag and then skipped testing that feature flag in CI.
Closes #831

feat: add support for devices request

---

testcontainers/Cargo.toml
testcontainers/src/core/client.rs
testcontainers/src/core/containers/request.rs
testcontainers/src/core/healthcheck.rs
testcontainers/src/core/image/image_ext.rs
testcontainers/src/core/ports.rs
testcontainers/src/lib.rs
testcontainers/src/runners/async_runner.rs
testcontainers/src/runners/sync_runner.rs

`bollard` already re-exports the correct version of the `bollard_stubs`, so use them directly. This makes it easier to work on and with `testcontainers-rs.`
I am unsure why we have an explicit dependency here, so just close this PR if there is a reason to have it this way.

refactor: remove bollard_stubs dependency as bollard re-exports it
