testcontainers/testcontainers-rs

images/parity_parity/src/image.rs, testcontainers/src/wait_for_message.rs
=> Activating tracing for parity

images/coblox_bitcoincore/Cargo.toml, images/parity_parity/Cargo.toml, images/trufflesuite_ganachecli/Cargo.toml, testcontainers/Cargo.toml
Bump minor versions of all images + testcontainers
This is to make the ecosystem change a opt-in.
=> Bump versions for release of new ecosystem

images/dynamodb_local/README.md, images/redis/Cargo.toml, images/redis/README.md, images/redis/src/image.rs, images/redis/src/lib.rs, testcontainers/Cargo.toml, testcontainers/src/lib.rs, testcontainers/tests/images.rs
Added a redis testcontainer image and fixed a mistake in the dynamo README.md
=> Adding Redis testcontainer image

images/coblox_bitcoincore/Cargo.toml, testcontainers/Cargo.toml
- tc_coblox_bitcoincore: (bitcoind 0.16.0 -> 0.17.0)
- tc_parity_parity (parity 1.11.11 -> 2.1.3)
=> Breaking Change - Upgrade to 0.4.0

.githooks/pre-commit, README.md
=> Add pre-commit hook and documentation

README.md, RELEASING.md
=> Add release guide

.travis.yml, Cargo.toml, images/generic/Cargo.toml, images/generic/README.md, images/generic/src/image.rs, images/generic/src/lib.rs, testcontainers/Cargo.toml, testcontainers/src/lib.rs, testcontainers/tests/images.rs
This is an attempt to solve  #56
It introduces a GenericImage implementation and a generic way of handling WaitFor strategies.
=> Add generic image

.travis.yml
=> Remove code coverage from travis

.travis.yml, Cargo.toml, images/postgres/Cargo.toml, images/postgres/README.md, images/postgres/src/image.rs, images/postgres/src/lib.rs, testcontainers/Cargo.toml, testcontainers/src/lib.rs, testcontainers/tests/images.rs
This PR adds support for a postgres image.
=> Add a postgres image

images/coblox_bitcoincore/src/image.rs
Related to comit-network/comit-rs#762
=> Allow configuration of acceptnonstdtxn option for Bitcoin Core

.travis.yml
- `cargo: cargo` now includes sccache
- the images are pulled whilest executing the test anyway
=> Simplify the .travis.yml confile file

tests/README.md
Since we are no longer using the microcrate approach, these tests don't need any further explanation.
=> Remove README.md from tests/ folder

src/clients/cli.rs, src/core/image.rs, src/images/coblox_bitcoincore.rs, src/images/dynamodb_local.rs, src/images/elasticmq.rs, src/images/generic.rs, src/images/parity_parity.rs, src/images/postgres.rs, src/images/redis.rs, src/images/trufflesuite_ganachecli.rs, tests/cli_client.rs
Fixes: #61.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
=> Add volume mapping support

src/images/postgres.rs, tests/images.rs
=> Password mandatory in postgres image

src/core/wait_for_message.rs
=> Return lines that read when returning EndOfStream error

Cargo.toml, src/images.rs, src/images/zookeeper.rs, tests/images.rs
Hi, this is my first contribution and i would like to contribute with kafka image for rust, but kafka needs for zookeeper, this is the zookeeper image and tomorrow should i will to publish kafka.
=> Create zookeeper image with him test.

Cargo.toml, src/images.rs, src/images/orientdb.rs, tests/images.rs
Hi, 
this PR add the support for OrientDB. 
I started out from the MongoDB one and added support for custom `env_vars`
=> Add OrientDB image

CHANGELOG.md, src/clients/cli.rs, src/core/docker.rs, src/core/image.rs, src/images/coblox_bitcoincore.rs, src/images/dynamodb_local.rs, src/images/elasticmq.rs, src/images/generic.rs, src/images/mongo.rs, src/images/orientdb.rs, src/images/parity_parity.rs, src/images/postgres.rs, src/images/redis.rs, src/images/trufflesuite_ganachecli.rs, src/images/zookeeper.rs, tests/cli_client.rs, tests/images.rs
=> extract identical port mapping logic from images to run args

src/images/postgres.rs, tests/images.rs
Adds a helper to allow customising the major version of the Psql image.
=> [images] Allow custom version for Postgres

CHANGELOG.md, src/core/container.rs, tests/images.rs
Closes #226.
@D4nte @luckysori any thoughts on why this change could be a really bad idea?
=> Make `get_host_port` panic if the port cannot be mapped

CHANGELOG.md, src/clients/cli.rs, src/core.rs, src/core/container.rs, src/core/env.rs
=> Replace `KEEP_CONTAINERS` env variable with `TESTCONTAINERS`

CHANGELOG.md, src/clients/cli.rs, src/core/wait_for_message.rs, src/images/elasticmq.rs, src/images/orientdb.rs, tests/images.rs
This fixes some failing tests: 
1. 58ff5c939c0520bcd38b774b231a3fe7ce45ef6c: Orientdb randomly fails in CI but not locally (tested on MacOS). 
I'll record issues for all the ignored tests once we are happy with this PR.
=> Fixing some failing tests

Cargo.toml
=> Use 0.7 release of shiplift

src/clients/cli.rs, src/clients/http.rs, src/core/container.rs, src/core/container_async.rs, src/core/docker.rs
=> Expose NetworkSettings.IPAddress

CHANGELOG.md, Cargo.toml, src/clients.rs, src/core.rs, src/core/logs.rs, src/lib.rs, tests/http_client.rs
This allows us to make a release without having to fix all the bugs.
=> Guard shiplift client behind experimental feature flag

src/clients/cli.rs, src/core/container_async.rs
* Reclaim zombie docker inspect command process
* Panic on unhealthy
=> Fix WaitFor::Healthcheck

.github/workflows/publish-new-release.yml, CHANGELOG.md, testcontainers/Cargo.toml
=> Release version 0.14.0

testcontainers/src/core/image.rs, testcontainers/src/core/ports.rs, testcontainers/src/images/google_cloud_sdk_emulators.rs, testcontainers/tests/images.rs
In this pr we address issue #376 implementing clippy suggested fixes.
=> nightly lint fixes

.github/docker.override.conf, .github/workflows/ci.yml, bors.toml
=> CI with `--all-features` and `--no-default-features`

testcontainers/src/core/container.rs, testcontainers/src/core/container_async.rs
Currently `get_bridge_ip_address` uses `NetworkSettings.IPAddress` which is [deprecated](https://docs.rs/bollard/latest/bollard/models/struct.NetworkSettings.html#structfield.ip_address)
So this PR uses `NetworkSettings.Networks` for that and perfectly combines with `network` (if it's passed to `Image)
~~Moreover in some cases it useful to use `inspect` result directly (it was mentioned [here](https://github.com/testcontainers/testcontainers-rs/pull/408#issuecomment-1272628962) as well)~~
=> fix: `get_bridge_ip_address`

CONTRIBUTING.md
See https://github.com/testcontainers/testcontainers-rs/issues/471
=> Remove image contributing reference

CHANGELOG.md, testcontainers/src/clients/cli.rs, testcontainers/tests/cli_client.rs, testimages/src/dockerfiles/no_expose_port.dockerfile, testimages/src/dockerfiles/simple_web_server.dockerfile
=> Remove explicit podman support

.github/workflows/ci.yml, .rustfmt.toml, Cargo.toml, dprint.json, testcontainers/Cargo.toml, testcontainers/src/clients/cli.rs, testcontainers/src/core/container.rs, testcontainers/src/core/container_async.rs, testcontainers/src/core/logs.rs, testimages/Cargo.toml
=> style: actualize formatting configs

testcontainers/Cargo.toml
It contains a fix of https://github.com/Xiphoseer/serde-java-properties/issues/3
=> chore(deps): update `serde-java-properties` to `0.2.0`

testcontainers/src/core/client.rs, testcontainers/src/core/containers/sync_container.rs, testcontainers/src/core/env.rs, testcontainers/src/core/env/config.rs, testcontainers/src/core/error.rs, testcontainers/src/lib.rs, testcontainers/src/runners/async_runner.rs, testcontainers/src/runners/sync_runner.rs
Follow-up PR after #636
Also removes outdated mentions of panics
=> fix: replace missed panics with `Result`

testcontainers/src/core/client.rs, testcontainers/src/core/containers/async_container.rs
This allows to handle eof of logs on client side
=> feat: map container not found error to `eof` for container log streams

LICENSE-MIT
=> chore: update authors

testcontainers/src/runners/sync_runner.rs
Include thread name and adjust number of workers
=> chore: re-configure blocking runtime

testcontainers/src/core/logs/consumer/logging_consumer.rs
Allow to set a custom prefix for log messages
=> feat: support optional prefix for `LoggingConsumer`

testcontainers/src/core/client.rs
That was wrong assumption about "unreachable" code.
StdIn still may occur, but we don't need this and explicitly pass only stderr & stdout flags. So for now it's simple filtering.
Closes #768
=> fix(768): proper handling of possible stdin in logs stream

testcontainers/src/core/containers/async_container.rs, testcontainers/src/core/containers/request.rs, testcontainers/src/core/image/image_ext.rs
This PR introduces part of changes proposed in #793
=> feat: allow ready conditions customization via ImageExt
